services:

  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      retries: 5
      timeout: 5s

  web:
    image: 192919965951.dkr.ecr.us-east-1.amazonaws.com/dogecr:latest
    pull_policy: always
    command: python app.py
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8000:5000"

  worker:
    image: 192919965951.dkr.ecr.us-east-1.amazonaws.com/dogecr:latest
    pull_policy: always
    command: celery -A celery_app worker --loglevel=info
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  db_data: